image: maven:3.9.5-amazoncorretto-17
stages:
  - checkstyle
  - test
  - build
  - build_image
  - push_image
variables:
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -Dcheckstyle.skip
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

cache:
  paths:
    - .m2/repository

checkstyle:
  stage: checkstyle
  script:
    - "mvn --batch-mode clean checkstyle:checkstyle"
test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean package
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
Build image:
  stage: build_image
  image: docker:latest
  services:
    - docker:dind
  script:
    docker build -t spring-petclinic .
