image: maven:3.9.5-amazoncorretto-17
stages:
  - checkstyle
  - test
  - build
  - push_image
variables:
  CONTAINER_REPO: "172.17.0.3:8082"
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -Dcheckstyle.skip
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

cache:
  paths:
    - .m2/repository

Checkstyle:
  stage: checkstyle
  script:
    - "mvn $MAVEN_CLI_OPTS checkstyle:checkstyle"
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

Test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

Build jar:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean package
  artifacts:
    paths: 
      - target/*.jar
    expire_in: 10 minutes
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

Push and build image (merge request):
  stage: push_image
  image:
    name: gcr.io/kaniko-project/executor:v1.18.0-debug
    entrypoint: [""]
  before_script:
    - 'echo "{ \"auths\": { \"${CONTAINER_REPO}\": { \"auth\": \"${NEXUS_LOGIN}\" } } }" > /kaniko/.docker/config.json'
  script:
    - /kaniko/executor
      --insecure
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CONTAINER_REPO}/mr:${CI_COMMIT_SHORT_SHA}"
  rules:
    - if: $CI_COMMIT_BRANCH == 'merge_request_event'

Push and build image (main branch):
  stage: push_image
  dependencies:
    - "Build jar"
  image:
    name: gcr.io/kaniko-project/executor:v1.18.0-debug
    entrypoint: [""]
  before_script:
    - 'echo "{ \"auths\": { \"${CONTAINER_REPO}\": { \"auth\": \"${NEXUS_LOGIN}\" } } }" > /kaniko/.docker/config.json'
  script:
    - /kaniko/executor
      --insecure
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CONTAINER_REPO}/main:latest"
    - /kaniko/executor
      --insecure
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CONTAINER_REPO}/main:${CI_COMMIT_SHORT_SHA}"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH