image: maven:3.9.5-amazoncorretto-17
stages:
  - checkstyle
  - test
  - build
  - push_image
variables:
  CONTAINER_REPO: "172.17.0.3:8082"
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -Dcheckstyle.skip
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

cache:
  paths:
    - .m2/repository

checkstyle-job:
  stage: checkstyle
  script:
    - "mvn -B checkstyle:checkstyle"
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

test-job:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

build_jar:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean package
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - "target/*"
    when: on_success
    expire_in: 30 minutes

push_image:
  stage: push_image
  dependencies:
    - "build_jar"
  image:
    name: gcr.io/kaniko-project/executor:v1.18.0-debug
    entrypoint: [""]
  before_script:
    - 'echo "{ \"auths\": { \"${CONTAINER_REPO}\": { \"auth\": \"${NEXUS_LOGIN}\" } } }" > /kaniko/.docker/config.json'
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then REPO_BRANCH="main"; fi
    - if [ "$CI_COMMIT_BRANCH" == "merge_request_event" ]; then REPO_BRANCH="mr"; fi
  script:
    - /kaniko/executor
      --insecure
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CONTAINER_REPO}/${REPO_BRANCH}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CONTAINER_REPO}/${REPO_BRANCH}:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'merge_request_event'