image: maven:3.9.5-amazoncorretto-17
stages:
  - checkstyle
  - test
  - build
  - push_image
variables:
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -Dcheckstyle.skip
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

cache:
  paths:
    - .m2/repository

Checkstyle:
  stage: checkstyle
  script:
    - "mvn --batch-mode clean checkstyle:checkstyle"
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

Test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

Build jar:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean package
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


Push and build image:
  stage: push_image
  image:
    name: gcr.io/kaniko-project/executor:v1.18.0-debug
    entrypoint: [""]
  script:
    - 'echo "{ \"auths\": { \"172.17.0.3:8082\": { \"auth\": \"${NEXUS_LOGIN}\" } } }" > /kaniko/.docker/config.json'
    - /kaniko/executor
      --insecure
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "172.17.0.3:8082/main:${CI_COMMIT_SHORT_SHA}"
  rules:
    - if: $CI_COMMIT_SHORT_SHA
