version: "3"
services:
  spring-petclinic:
    build: .
    image: spring-petclinic:latest
    ports:
      - "8080:8080"
    command: [ "java", "-jar", "-javaagent:./jmx.jar=9090:config.yaml", "-Dspring.profiles.active=postgres", "petclinic.jar"]
    env_file:
      - postgres.env
    depends_on:
      - postgres
  postgres:
    image: postgres:16.1
    volumes:
      - type: volume
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    env_file:
      - postgres.env
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ~/petclinic-configs/prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    