version: "3"

services:
  spring-petclinic:
    build: .
    image: spring-petclinic:latest
    ports:
      - "8080:8080"
    command: [ "java", "-jar", "-Dspring.profiles.active=postgres", "petclinic.jar"]
    env_file:
      - postgres.env
    depends_on:
      - postgres
  postgres:
    image: postgres:15.3
    volumes:
      - type: volume
        target: /var/lib/postgresql/data
    env_file:
      - postgres.env
