version: "3"

services:
  spring-petclinic:
    build: .
    image: spring-petclinic:latest
    ports:
      - "8080:8080"
    command: [ "java", "-jar", "-Dspring.profiles.active=postgres", "-Dspring.datasource.url=jdbc:postgresql://postgres/petclinic", "petclinic.jar"]
    depends_on:
      - postgres
  postgres:
    image: postgres:15.3
    volumes:
      - type: volume
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
