apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  labels:
    app: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: mlabecki/spring-petclinic:latest
        ports:
        - containerPort: 8080
        command: ["java"]
        args: [ "-Dspring.profiles.active=postgres", "-jar", "petclinic.jar"]
        env:  
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: main-app-config
              key: postgres-host
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: main-app-config
              key: postgres-user
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: main-app-config
              key: postgres-db
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: main-app-lb
spec:
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: main-app-config
data:
  postgres-host: postgres-postgresql
  postgres-user: postgres
  postgres-db: postgres